### ISSUE TITLE
RuntimeError: Unsupported platform architecture: darwin arm64

### ISSUE THREAD

**Issue by Janaka-Steph** [DreamedAtlas/tor-downloader#11]
System MacOS M1 12.6

```
error RuntimeError: Unsupported platform architecture: darwin arm64
    at Function.fromNodeValues (/Users/stephane/Desktop/unstoppableswap-gui/node_modules/@dreamed-atlas/tor-downloader/dist/tor-browser/PlatformArch.js:42:19)
    at Function.fromValues (/Users/stephane/Desktop/unstoppableswap-gui/node_modules/@dreamed-atlas/tor-downloader/dist/tor-browser/Release.js:21:65)
    at Release.getMarToolsRelease (/Users/stephane/Desktop/unstoppableswap-gui/node_modules/@dreamed-atlas/tor-downloader/dist/tor-browser/Release.js:45:24)
    at TorDownloader.<anonymous> (/Users/stephane/Desktop/unstoppableswap-gui/node_modules/@dreamed-atlas/tor-downloader/dist/TorDownloader.js:150:92)
    at Generator.next (<anonymous>)
    at /Users/stephane/Desktop/unstoppableswap-gui/node_modules/@dreamed-atlas/tor-downloader/dist/TorDownloader.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/stephane/Desktop/unstoppableswap-gui/node_modules/@dreamed-atlas/tor-downloader/dist/TorDownloader.js:4:12)
    at /Users/stephane/Desktop/unstoppableswap-gui/node_modules/@dreamed-atlas/tor-downloader/dist/TorDownloader.js:149:28
    at TorDownloader.<anonymous> (/Users/stephane/Desktop/unstoppableswap-gui/node_modules/@dreamed-atlas/tor-downloader/dist/TorDownloader.js:152:24)

```

**Comment by Gta-Cool** [comment]
Hello,

Unfortunately, this library heavily depends on Tor Browser (Tor binary is extracted from the Tor Browser archive), which is not distributed yet for arm64.

Did you try to specifically download the x64 version and run it with rosetta?

There is an issue on the Tor GitLab about porting Tor Browser for macOS aarch64:
https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/issues/40158

I'm closing for now. Feel free to comment if necessary.
